language: php

sudo: false

env:
    global:
        secure: "MojGxVh2lskCUe2O6wbs9rcbX3ot/4dXsVnBJfHBnnN8IIRCeMnVSwvgYVjQahi8KzEv6FA62IL8L8VeC0Aik4MY8aZszWv2bqg0Vyhb3K0RXjwqJ1OCkRnkhHHSU4KahLhEW2bqZDUgqCcTPZM5Hb7BofYXSAuMUgDgzIrLLS1D//EI4A2A4WHqjkJX8et5RXkFvJS2VSpvAgJWwhqAlfqEphu8imASJZQZ9BB7IFriwK97vigwLJWG7LAeN5aRZ1leRAwg3ooltnpfZUUCxUmL1G5fOQdxUK79DVHUzn4cy5k7HIrF4hHmb+yOahqTaKyBBBBGW1MYtLS83tvqDHfpU8o0Q5BiJqqnGfCAyKVIY2Vg9AF96I6Sgt/6aoJy8UtP8VSoAA8vzJjOyj0Dh0MsiAv6CP+lBHoqZCj2cfyFsPp8Vju/gSpIaGUXmJE7HNTh4RXZygjou6lzril5wTc8a3NS0Ymak2i5oDMiHOrVyZCAhfNBa8VXO7AQntZJQHFTHXX+pR0tzPI5xplsbC8trEjKJg/h6gdm7kiuZbDVPsT6IJXzdlTp8L4IOoJlaGd6Np32middcqHUKDSPiweLyKQKHJOVs0OFVltn0DT98FN1aTSs1c85t7v9ahamrLuAxgMUt7YS7f4xYUo1TZ1ek6nfXXt8/RsjYuhgl2I="

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

before_script:
  - php --version
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer config github-oauth.github.com ${GITHUBTOKEN}
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:1.0.0 --prefer-dist
  - travis_retry composer install --no-interaction --prefer-dist
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --debug

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
